<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import NxAlert from '../../components/ui/NxAlert.vue';
import NxBadge from '../../components/ui/NxBadge.vue';
import NxButton from '../../components/ui/NxButton.vue';
import NxCard from '../../components/ui/NxCard.vue';
import NxConfirmDialog from '../../components/ui/NxConfirmDialog.vue';
import NxPageHeader from '../../components/ui/NxPageHeader.vue';
import NxTableShell from '../../components/ui/NxTableShell.vue';
import NxToolbar from '../../components/ui/NxToolbar.vue';
import { applyCgnat, getCgnat, removePostroutingRules, saveCgnat } from './api';
import type { CgnatConfig, CgnatRuntime } from './contracts';

type Tab = 'config' | 'rules';
type Action = 'apply' | 'remove';
const emptyConfig = (): CgnatConfig => ({ enabled: 1, inside_network: '', bng_interface: '', public_start_ip: '', public_end_ip: '', egress_interface: '' });
const tab = ref<Tab>('config'); const loading = ref(false); const saving = ref(false); const dirty = ref(false);
const error = ref(''); const notice = ref(''); const dialogError = ref(''); const pendingAction = ref<Action | null>(null);
const runtime = ref<CgnatRuntime>({}); const selected = ref<string[]>([]); const form = reactive<CgnatConfig>(emptyConfig());
const rules = computed(() => runtime.value.nat_rules || []);
const removableCount = computed(() => rules.value.filter((rule) => rule.removable).length);
const summaryCards = computed(() => [
  ['Desired State', form.id ? (form.enabled ? 'Enabled' : 'Disabled') : 'Not configured', dirty.value ? 'Unsaved edits' : (form.id ? 'Saved configuration' : 'Save a draft before applying')],
  ['Subscriber Network', form.inside_network || 'Not configured', `BNG: ${form.bng_interface || '—'}`],
  ['Public Range', form.public_start_ip || 'Not configured', form.public_end_ip ? `Through ${form.public_end_ip}` : 'No end address'],
  ['Live Rules', rules.value.length, `${removableCount.value} removable`],
]);
const actionCopy = computed(() => pendingAction.value === 'remove'
  ? { title: 'Remove selected live rules?', description: `This removes ${selected.value.length} exact POSTROUTING rule${selected.value.length === 1 ? '' : 's'} from the BNG immediately. Subscriber traffic may lose NAT access.`, label: 'Remove Rules', danger: true }
  : { title: 'Apply saved CGNAT configuration?', description: `${form.inside_network || 'Subscriber traffic'} will use ${form.egress_interface || 'the egress interface'} and public range ${form.public_start_ip || '—'} to ${form.public_end_ip || '—'}. This changes live addresses and iptables state on the BNG.`, label: 'Apply CGNAT State', danger: false });

function clearMessages() { error.value = ''; notice.value = ''; dialogError.value = ''; }
function hydrate(config?: Partial<CgnatConfig> | null) { Object.assign(form, emptyConfig(), config || {}, { enabled: Number(config?.enabled ?? 1) }); dirty.value = false; }
async function load(showNotice = false) { loading.value = true; clearMessages(); try { const data = await getCgnat(); hydrate(data.config); runtime.value = data.runtime || {}; selected.value = []; if (showNotice) notice.value = 'CGNAT runtime refreshed.'; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Failed to load CGNAT.'; } finally { loading.value = false; } }
function markDirty() { dirty.value = true; notice.value = ''; }
async function submit() { saving.value = true; clearMessages(); try { const result = await saveCgnat({ ...form }); notice.value = result.message || 'CGNAT configuration saved. Live BNG state was not changed.'; await load(false); notice.value = result.message || 'CGNAT configuration saved. Live BNG state was not changed.'; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Failed to save CGNAT configuration.'; } finally { saving.value = false; } }
function requestAction(action: Action) { clearMessages(); pendingAction.value = action; }
async function executeAction() { if (!pendingAction.value) return; saving.value = true; dialogError.value = ''; try { const result = pendingAction.value === 'apply' ? await applyCgnat() : await removePostroutingRules(selected.value); const message = result.message; pendingAction.value = null; await load(false); notice.value = message; } catch (reason) { dialogError.value = reason instanceof Error ? reason.message : 'CGNAT action failed.'; } finally { saving.value = false; } }
function toggle(hash: string, checked: boolean) { selected.value = checked ? [...new Set([...selected.value, hash])] : selected.value.filter((item) => item !== hash); }
onMounted(() => void load(false));
</script>

<template><div class="space-y-4 pb-8 text-[var(--nx-text)]">
  <NxPageHeader eyebrow="Address translation" title="CGNAT Management" description="Manage subscriber address translation and inspect live POSTROUTING state independently from Accel-PPP."><template #actions><a href="/bng" class="inline-flex min-h-10 items-center rounded-md border border-[var(--nx-border)] bg-[var(--nx-surface)] px-4 text-sm font-semibold text-[var(--nx-text)] no-underline">Open BNG Management</a></template></NxPageHeader>
  <NxAlert v-if="error || notice" :tone="error ? 'danger' : 'success'">{{ error || notice }}</NxAlert>
  <NxAlert v-if="runtime.warning" tone="warning">{{ runtime.warning }}</NxAlert>
  <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><NxCard v-for="item in summaryCards" :key="String(item[0])"><p class="text-xs font-semibold uppercase text-[var(--nx-text-muted)]">{{ item[0] }}</p><p class="mt-2 text-xl font-bold">{{ item[1] }}</p><p class="mt-1 text-xs text-[var(--nx-text-muted)]">{{ item[2] }}</p></NxCard></section>
  <NxToolbar><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div role="tablist" aria-label="CGNAT views" class="flex flex-wrap gap-2"><button v-for="item in [['config','CGNAT Configuration'],['rules','Live POSTROUTING Rules']]" :key="item[0]" class="min-h-10 rounded-md px-3 text-sm font-semibold" :class="tab === item[0] ? 'bg-brand-600 text-white' : 'bg-[var(--nx-surface-muted)] text-[var(--nx-text)]'" @click="tab = item[0] as Tab">{{ item[1] }}</button></div><NxButton variant="secondary" :disabled="loading" @click="load(true)">{{ loading ? 'Refreshing…' : 'Refresh Runtime' }}</NxButton></div></NxToolbar>
  <section v-if="tab === 'config'" class="rounded-lg border border-[var(--nx-border)] bg-[var(--nx-surface)] shadow-sm"><div class="border-b border-[var(--nx-border)] p-5"><h2 class="font-bold">Desired POSTROUTING configuration</h2><p class="text-sm text-[var(--nx-text-muted)]">Saving updates the database draft only. Applying is a separate live operation.</p></div><form @submit.prevent="submit"><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3"><label class="grid gap-1.5 text-sm font-semibold">Status<select v-model.number="form.enabled" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3" @change="markDirty"><option :value="1">Enabled</option><option :value="0">Disabled</option></select></label><label class="grid gap-1.5 text-sm font-semibold">Subscriber network<input v-model="form.inside_network" required placeholder="100.64.0.0/24" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono" @input="markDirty"></label><label class="grid gap-1.5 text-sm font-semibold">BNG interface<input v-model="form.bng_interface" required list="nx-cgnat-interfaces" placeholder="ens17" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono" @input="markDirty"><span class="text-xs font-normal text-[var(--nx-text-muted)]">Physical Linux interface only.</span></label><label class="grid gap-1.5 text-sm font-semibold">Public egress interface<input v-model="form.egress_interface" required list="nx-cgnat-interfaces" placeholder="ens16" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono" @input="markDirty"></label><label class="grid gap-1.5 text-sm font-semibold">Public start IP<input v-model="form.public_start_ip" required placeholder="126.209.31.170" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono" @input="markDirty"></label><label class="grid gap-1.5 text-sm font-semibold">Public end IP<input v-model="form.public_end_ip" required placeholder="126.209.31.174" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono" @input="markDirty"></label><datalist id="nx-cgnat-interfaces"><option v-for="iface in runtime.interfaces || []" :key="iface" :value="iface" /></datalist></div><div class="flex flex-wrap justify-end gap-2 border-t border-[var(--nx-border)] p-5"><NxBadge v-if="dirty" tone="warning">Unsaved changes</NxBadge><NxButton type="submit" :disabled="saving || !dirty">{{ saving ? 'Saving…' : 'Save Configuration' }}</NxButton><NxButton type="button" variant="secondary" :disabled="saving || dirty || !form.id" @click="requestAction('apply')">Apply CGNAT State</NxButton></div></form></section>
  <section v-if="tab === 'rules'" class="space-y-3"><NxAlert tone="warning">A saved enabled CGNAT configuration may restore its managed SNAT rule during reconciliation. Update or disable desired configuration for permanent removal.</NxAlert><div class="flex justify-end"><NxButton variant="danger" :disabled="!selected.length" @click="requestAction('remove')">Remove Selected ({{ selected.length }})</NxButton></div><NxTableShell min-width="860px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase text-[var(--nx-text-muted)]"><tr><th class="w-14 px-4 py-3">Select</th><th class="px-4 py-3">Live rule</th><th class="px-4 py-3">Control</th></tr></thead><tbody><tr v-if="loading"><td colspan="3" class="px-4 py-12 text-center">Loading live rules…</td></tr><tr v-else-if="!rules.length"><td colspan="3" class="px-4 py-12 text-center">No POSTROUTING rules reported.</td></tr><tr v-for="rule in rules" :key="rule.hash || rule.rule"><td class="px-4 py-3"><input v-if="rule.removable" type="checkbox" :checked="selected.includes(rule.hash)" :aria-label="`Select ${rule.rule}`" class="size-4 accent-brand-600" @change="toggle(rule.hash, ($event.target as HTMLInputElement).checked)"></td><td class="break-all px-4 py-3 font-mono text-xs">{{ rule.rule }}</td><td class="px-4 py-3"><NxBadge :tone="rule.removable ? 'warning' : 'neutral'">{{ rule.removable ? 'REMOVABLE' : 'READ ONLY' }}</NxBadge></td></tr></tbody></NxTableShell></section>
  <NxConfirmDialog :open="Boolean(pendingAction)" :title="actionCopy.title" :description="actionCopy.description" :confirm-label="actionCopy.label" :busy="saving" :danger="actionCopy.danger" :error="dialogError" @close="pendingAction = null" @confirm="executeAction" />
</div></template>
