<?php
$routersLegacyUi = isset($_GET['legacy_ui']) && (string)$_GET['legacy_ui'] === '1';
if (!$routersLegacyUi):
    $nxNextManifestPath = BASE_PATH . '/public/build-next/.vite/manifest.json';
    $nxNextManifest = is_file($nxNextManifestPath) ? (json_decode((string)file_get_contents($nxNextManifestPath), true) ?: []) : [];
    $nxNextEntry = $nxNextManifest['src/main.ts'] ?? [];
    $nxNextVersion = is_file($nxNextManifestPath) ? (string)filemtime($nxNextManifestPath) : (string)time();
    foreach (($nxNextEntry['css'] ?? []) as $nxNextCss): ?>
        <link rel="stylesheet" href="/build-next/<?= htmlspecialchars(ltrim((string)$nxNextCss, '/'), ENT_QUOTES, 'UTF-8') ?>?v=<?= htmlspecialchars($nxNextVersion, ENT_QUOTES, 'UTF-8') ?>">
    <?php endforeach; ?>
    <div class="container-fluid nx-page" data-nx-next-root="routers"></div>
    <?php if (!empty($nxNextEntry['file'])): ?>
        <script type="module" src="/build-next/<?= htmlspecialchars(ltrim((string)$nxNextEntry['file'], '/'), ENT_QUOTES, 'UTF-8') ?>?v=<?= htmlspecialchars($nxNextVersion, ENT_QUOTES, 'UTF-8') ?>"></script>
    <?php else: ?>
        <div class="alert alert-warning">The new Routers interface is not built. Use <a href="/routers?legacy_ui=1">the legacy interface</a>.</div>
    <?php endif;
    return;
endif;
?>

<div class="container-fluid nx-page" id="routerManagementApp">
<div class="card border-0 shadow-sm mb-4 nx-page-header-card page-hero-card"><div class="card-body page-hero-body"><div class="page-hero-left"><div class="page-hero-badge"><i class="bi bi-signpost-split"></i><span>Routing Infrastructure</span></div><h1 class="page-hero-title">Routers</h1><p class="page-hero-text">Manage the Juniper backbone router and the FRRouting instance running on the BNG server.</p></div></div></div>
<div class="nx-toolbar-card mb-3"><div class="nx-segment-control" role="tablist" aria-label="Router views"><button class="nx-segment-control__item active" type="button" data-router-tab-btn="core">Core Router</button><button class="nx-segment-control__item" type="button" data-router-tab-btn="frr">FRR Router</button></div></div>

<section data-router-tab="core" class="card border-0 shadow-sm nx-content-card"><div class="subs-table-topline"></div><div class="card-body border-bottom d-flex justify-content-between"><div><div class="fw-semibold">Juniper Core Router</div><div class="text-muted small">Backbone routing, BGP peering, public-prefix route, and the physical link to the BNG.</div></div><div class="d-flex gap-2"><button class="btn btn-sm btn-light border" id="routerCoreTrustBtn" type="button">Trust Host Key</button><button class="btn btn-sm btn-light border" id="routerCoreRefreshBtn" type="button">Refresh Runtime</button></div></div><form id="routerCoreForm"><div class="card-body"><div class="row g-3">
<?php $coreFields=[['host','Management IP / host','text','10.0.15.6'],['port','SSH port','number','22'],['username','Username','text','root'],['password','Password','password','Leave blank to keep saved password'],['autonomous_system','Local AS','number','65000'],['default_next_hop','Default next hop','text','10.0.26.1'],['public_prefix','Public prefix','text','126.209.31.168/29'],['bng_next_hop','BNG next hop','text','10.255.255.2'],['bgp_group','BGP group','text','BNG'],['local_address','BGP local address','text','10.255.255.1'],['peer_as','Peer AS','number','65001'],['neighbor','BGP neighbor','text','10.255.255.2'],['interface_name','BNG link interface','text','xe-0/1/6'],['interface_description','Interface description','text','LINK TO BNG SERVER'],['interface_address','Interface address','text','10.255.255.1/30']];foreach($coreFields as[$name,$label,$type,$placeholder]):?><div class="col-md-6 col-xl-4"><label class="form-label"><?=htmlspecialchars($label)?></label><input class="form-control" name="<?=htmlspecialchars($name)?>" type="<?=$type?>" placeholder="<?=htmlspecialchars($placeholder)?>" <?=$name==='password'?'autocomplete="new-password"':''?> <?=$name==='password'?'':'required'?>></div><?php endforeach;?></div><input type="hidden" name="enabled" value="1"><div class="d-flex justify-content-end gap-2 border-top pt-3 mt-3"><button class="btn btn-primary" type="submit">Save Draft</button><button class="btn btn-danger" type="button" id="routerCoreApplyBtn">Apply to Core Router</button></div></div></form><div class="row g-0 border-top"><div class="col-xl-6 border-end"><div class="p-3 fw-semibold">Generated Junos configuration</div><pre class="bg-dark text-light p-3 m-0 overflow-auto" id="routerCorePreview">Save a draft to generate the configuration.</pre></div><div class="col-xl-6"><div class="p-3 fw-semibold">Live runtime</div><pre class="bg-dark text-light p-3 m-0 overflow-auto" id="routerCoreRuntime">Use Refresh Runtime after the host key is trusted.</pre></div></div></section>

<section data-router-tab="frr" class="card border-0 shadow-sm nx-content-card d-none"><div class="subs-table-topline"></div><div class="card-body border-bottom d-flex justify-content-between"><div><div class="fw-semibold">FRR Router on BNG</div><div class="text-muted small">Uses the existing trusted BNG SSH connection and runs vtysh locally on that Linux server.</div></div><button class="btn btn-sm btn-light border" id="routerFrrRefreshBtn" type="button">Refresh Runtime</button></div><form id="routerFrrForm"><div class="card-body"><div class="row g-3">
<?php $frrFields=[['autonomous_system','Local AS','65001'],['router_id','Router ID','10.255.255.2'],['neighbor','BGP neighbor','10.255.255.1'],['remote_as','Remote AS','65000'],['subscriber_network','Subscriber network','100.64.0.0/24'],['in_prefix_list','Inbound prefix list','PL-DEFAULT'],['out_prefix_list','Outbound prefix list','PL-SUBS'],['in_route_map','Inbound route map','RM-IN-DEFAULT'],['out_route_map','Outbound route map','RM-OUT-SUBS']];foreach($frrFields as[$name,$label,$placeholder]):?><div class="col-md-6 col-xl-4"><label class="form-label"><?=htmlspecialchars($label)?></label><input class="form-control" name="<?=htmlspecialchars($name)?>" placeholder="<?=htmlspecialchars($placeholder)?>" required></div><?php endforeach;?></div><input type="hidden" name="enabled" value="1"><div class="d-flex justify-content-end gap-2 border-top pt-3 mt-3"><button class="btn btn-primary" type="submit">Save Draft</button><button class="btn btn-danger" type="button" id="routerFrrApplyBtn">Apply through vtysh</button></div></div></form><div class="row g-0 border-top"><div class="col-xl-6 border-end"><div class="p-3 fw-semibold">Generated FRR configuration</div><pre class="bg-dark text-light p-3 m-0 overflow-auto" id="routerFrrPreview">Save a draft to generate the configuration.</pre></div><div class="col-xl-6"><div class="p-3 fw-semibold">Live vtysh runtime</div><pre class="bg-dark text-light p-3 m-0 overflow-auto" id="routerFrrRuntime">Use Refresh Runtime to read the BNG FRR configuration.</pre></div></div></section>
<script src="/module-assets/RouterManagement/js/RouterManagement.js?v=router2"></script></div>
