<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import NxAlert from '../../components/ui/NxAlert.vue';
import NxBadge from '../../components/ui/NxBadge.vue';
import NxButton from '../../components/ui/NxButton.vue';
import NxCard from '../../components/ui/NxCard.vue';
import NxModal from '../../components/ui/NxModal.vue';
import NxPageHeader from '../../components/ui/NxPageHeader.vue';
import NxTableShell from '../../components/ui/NxTableShell.vue';
import { list, post, rows, type Row } from './api';

const busy=ref(false),loading=ref(false),error=ref(''),notice=ref(''),resultOpen=ref(false),resultTitle=ref(''),result=ref<any>(null);
const subscribers=ref<Row[]>([]),plans=ref<Row[]>([]),onts=ref<Row[]>([]),olts=ref<Row[]>([]),ports=ref<Row[]>([]),naps=ref<Row[]>([]),splitters=ref<Row[]>([]),splitterPorts=ref<Row[]>([]),jobs=ref<Row[]>([]);
const form=reactive({subscriber_id:'',plan_id:'',ont_id:'',olt_id:'',olt_port_id:'',network_box_id:'',splitter_id:'',splitter_output_port_id:''});
const selected=(items:Row[],id:string)=>items.find(r=>String(r.id??r.plan_id)===String(id));
const ontSerial=computed(()=>String(selected(onts.value,form.ont_id)?.serial_number||''));
const payload=computed(()=>{const p=selected(plans.value,form.plan_id);return{subscriber_id:form.subscriber_id,plan_id:p?.plan_id||p?.id||form.plan_id,service_id:p?.service_id||'',ont_id:form.ont_id,ont_serial:ontSerial.value,olt_id:form.olt_id,olt_port_id:form.olt_port_id,network_box_id:form.network_box_id,splitter_id:form.splitter_id,splitter_output_port_id:form.splitter_output_port_id,provision_mode:'FULL_AUTO'};});
const readiness=computed(()=>[
 ['Customer',!!form.subscriber_id&&!!form.plan_id],['ONT inventory',!!form.ont_id],['PON path',!!form.olt_id&&!!form.olt_port_id],['NAP and splitter',!!form.network_box_id&&!!form.splitter_id&&!!form.splitter_output_port_id],['VLAN and profiles',!!form.plan_id&&!!form.olt_port_id]
] as [string,boolean][]);
const ready=computed(()=>readiness.value.every(([,ok])=>ok));
const label=(r?:Row,...keys:string[])=>keys.map(k=>r?.[k]).find(Boolean)||`#${r?.id??'—'}`;
const fieldClass='min-h-11 w-full rounded-md border border-[var(--nx-border)] bg-[var(--nx-surface)] px-3 text-sm text-[var(--nx-text)]';
async function loadAll(show=false){loading.value=true;error.value='';try{const [s,p,o,ol,j]=await Promise.all([list('/api/v1/service-provisioning/support/subscribers'),list('/api/v1/service-provisioning/support/plans'),list('/api/v1/service-provisioning/support/onts'),list('/api/v1/service-provisioning/support/olts'),list<any>('/api/v1/service-provisioning/list?page=1&limit=10')]);subscribers.value=rows(s);plans.value=rows(p);onts.value=rows(o);olts.value=rows(ol);jobs.value=rows(j);if(show)notice.value='Provisioning workspace refreshed.';}catch(e){error.value=e instanceof Error?e.message:'Unable to load provisioning workspace.';}finally{loading.value=false;}}
async function cascade(target:'plans'|'ports'|'naps'|'splitters'|'splitterPorts',url:string){try{const data=rows(await list(url));if(target==='plans')plans.value=data;else if(target==='ports')ports.value=data;else if(target==='naps')naps.value=data;else if(target==='splitters')splitters.value=data;else splitterPorts.value=data.filter(r=>String(r.status||'').toUpperCase()==='AVAILABLE');}catch(e){error.value=e instanceof Error?e.message:'Unable to load options.';}}
watch(()=>form.subscriber_id,v=>{form.plan_id='';void cascade('plans',`/api/v1/service-provisioning/support/plans${v?`?subscriber_id=${encodeURIComponent(v)}`:''}`);});
watch(()=>form.olt_id,v=>{form.olt_port_id=form.network_box_id=form.splitter_id=form.splitter_output_port_id='';ports.value=naps.value=splitters.value=splitterPorts.value=[];if(v)void cascade('ports',`/api/v1/service-provisioning/support/olt-ports?olt_id=${encodeURIComponent(v)}`);});
watch(()=>form.olt_port_id,v=>{form.network_box_id=form.splitter_id=form.splitter_output_port_id='';naps.value=splitters.value=splitterPorts.value=[];if(v)void cascade('naps',`/api/v1/service-provisioning/support/network-boxes?olt_id=${encodeURIComponent(form.olt_id)}&olt_port_id=${encodeURIComponent(v)}&box_type=NAP`);});
watch(()=>form.network_box_id,v=>{form.splitter_id=form.splitter_output_port_id='';splitters.value=splitterPorts.value=[];if(v)void cascade('splitters',`/api/v1/service-provisioning/support/splitters?network_box_id=${encodeURIComponent(v)}`);});
watch(()=>form.splitter_id,v=>{form.splitter_output_port_id='';splitterPorts.value=[];if(v)void cascade('splitterPorts',`/api/v1/service-provisioning/support/splitter-output-ports?splitter_id=${encodeURIComponent(v)}`);});
function showResult(title:string,data:any){resultTitle.value=title;result.value=data;resultOpen.value=true;}
async function validate(){if(!ready.value)return;busy.value=true;error.value='';try{showResult('Validation Successful',await post('/api/v1/service-provisioning/validate',payload.value));}catch(e){error.value=e instanceof Error?e.message:'Validation failed.';showResult('Validation Failed',{message:error.value});}finally{busy.value=false;}}
async function activate(){if(!ready.value||!confirm('Activate this subscriber service now? This will provision network and subscriber resources.'))return;busy.value=true;error.value='';try{const created=await post('/api/v1/service-provisioning/create',payload.value),jobId=Number(created?.job_id||created?.id||0);if(!jobId)throw new Error('Provisioning job ID was not returned.');const run=await post('/api/v1/service-provisioning/run',{job_id:jobId});let acs=await post(`/api/v1/service-provisioning/check-acs/${jobId}`);for(let attempt=1;!acs?.acs_found&&attempt<=18;attempt++){notice.value=`Job #${jobId}: waiting for ACS (${attempt}/18)…`;await new Promise(resolve=>window.setTimeout(resolve,10000));acs=await post(`/api/v1/service-provisioning/check-acs/${jobId}`);}showResult(acs?.acs_found?'Activation Completed':'Waiting for ACS',{job_id:jobId,run,acs});notice.value=acs?.acs_found?`Provisioning job #${jobId} completed.`:`Job #${jobId} provisioned and is waiting for ACS.`;await loadAll();}catch(e){error.value=e instanceof Error?e.message:'Activation failed.';showResult('Activation Failed',{message:error.value});}finally{busy.value=false;}}
async function jobAction(job:Row,action:'cancel'|'retry'|'check-acs'){if(!confirm(`${action==='check-acs'?'Check ACS for':action==='retry'?'Retry':'Cancel'} job #${job.id}?`))return;busy.value=true;try{const url=action==='check-acs'?`/api/v1/service-provisioning/check-acs/${job.id}`:`/api/v1/service-provisioning/${action}/${job.id}`;showResult('Job Updated',await post(url));await loadAll();}catch(e){error.value=e instanceof Error?e.message:'Job action failed.';}finally{busy.value=false;}}
function tone(v:any):'success'|'danger'|'warning'|'neutral'{const s=String(v||'').toUpperCase();return s==='SUCCESS'||s==='COMPLETED'?'success':s==='FAILED'?'danger':['READY','VERIFYING','PENDING'].includes(s)?'warning':'neutral';}
onMounted(()=>void loadAll());
</script>

<template><div class="space-y-4 pb-8 text-[var(--nx-text)]"><NxPageHeader eyebrow="FTTH service activation" title="Service Provisioning" description="Validate the complete subscriber path before controlled activation."><template #actions><NxButton variant="secondary" :disabled="loading||busy" @click="loadAll(true)">{{loading?'Refreshing…':'Refresh'}}</NxButton><NxButton variant="secondary" :disabled="busy||!ready" @click="validate">Validate</NxButton><NxButton :disabled="busy||!ready" @click="activate">{{busy?'Working…':'Activate Service'}}</NxButton></template></NxPageHeader><NxAlert v-if="error||notice" :tone="error?'danger':'success'">{{error||notice}}</NxAlert>
<div class="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><NxCard><div class="border-b border-[var(--nx-border)] p-5"><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Activation Builder</p><h2 class="mt-1 text-lg font-bold">Subscriber Service Setup</h2></div><div class="grid gap-6 p-5 md:grid-cols-2">
<label class="grid gap-2 text-sm font-semibold">Subscriber<select v-model="form.subscriber_id" :class="fieldClass"><option value="">Select subscriber</option><option v-for="r in subscribers" :key="r.id" :value="r.id">{{label(r,'full_name','name')}} · {{r.account_number||r.id}}</option></select></label><label class="grid gap-2 text-sm font-semibold">Service / Plan<select v-model="form.plan_id" :class="fieldClass"><option value="">Select plan</option><option v-for="r in plans" :key="r.plan_id||r.id" :value="r.plan_id||r.id">{{label(r,'plan_name','name')}} · {{r.speed_mbps?`${r.speed_mbps} Mbps`:''}}</option></select></label>
<label class="grid gap-2 text-sm font-semibold md:col-span-2">ONT Device<select v-model="form.ont_id" :class="fieldClass"><option value="">Select known ONT</option><option v-for="r in onts" :key="r.id" :value="r.id">{{r.serial_number}} · {{label(r,'model','vendor')}}</option></select></label>
<label class="grid gap-2 text-sm font-semibold">OLT<select v-model="form.olt_id" :class="fieldClass"><option value="">Select OLT</option><option v-for="r in olts" :key="r.id" :value="r.id">{{label(r,'name')}} · {{r.ip_address||''}}</option></select></label><label class="grid gap-2 text-sm font-semibold">PON Port<select v-model="form.olt_port_id" :class="fieldClass"><option value="">Select PON port</option><option v-for="r in ports" :key="r.id" :value="r.id">{{r.label||`${r.frame??0}/${r.slot??0}/${r.port??0}`}} · {{r.ont_count||0}}/16 ONTs</option></select></label>
<label class="grid gap-2 text-sm font-semibold">NAP Box<select v-model="form.network_box_id" :class="fieldClass"><option value="">Select NAP</option><option v-for="r in naps" :key="r.id" :value="r.id">{{label(r,'box_name','box_code')}}</option></select></label><label class="grid gap-2 text-sm font-semibold">Splitter<select v-model="form.splitter_id" :class="fieldClass"><option value="">Select splitter</option><option v-for="r in splitters" :key="r.id" :value="r.id">{{label(r,'splitter_model')}} · 1:{{r.splitter_ratio||'—'}}</option></select></label><label class="grid gap-2 text-sm font-semibold md:col-span-2">Splitter Output Port<select v-model="form.splitter_output_port_id" :class="fieldClass"><option value="">Select available output port</option><option v-for="r in splitterPorts" :key="r.id" :value="r.id">Port {{r.port_number}}{{r.reserved_label?` · ${r.reserved_label}`:''}}</option></select></label></div></NxCard>
<div class="space-y-4"><NxCard><div class="p-5"><p class="text-xs font-bold uppercase text-[var(--nx-text-muted)]">Readiness</p><div class="mt-4 space-y-3"><div v-for="[name,ok] in readiness" :key="name" class="flex items-center justify-between rounded-md bg-[var(--nx-surface-muted)] px-3 py-3"><span class="text-sm font-semibold">{{name}}</span><NxBadge :tone="ok?'success':'neutral'">{{ok?'READY':'PENDING'}}</NxBadge></div></div></div></NxCard><NxCard><div class="p-5"><p class="text-xs font-bold uppercase text-[var(--nx-text-muted)]">Selected Chain</p><dl class="mt-4 grid gap-3 text-sm"><div><dt class="text-[var(--nx-text-muted)]">Subscriber</dt><dd class="font-semibold">{{label(selected(subscribers,form.subscriber_id),'full_name','name')}}</dd></div><div><dt class="text-[var(--nx-text-muted)]">ONT</dt><dd class="font-mono font-semibold">{{ontSerial||'—'}}</dd></div><div><dt class="text-[var(--nx-text-muted)]">Network Path</dt><dd class="font-semibold">{{label(selected(olts,form.olt_id),'name')}} → {{label(selected(naps,form.network_box_id),'box_name','box_code')}}</dd></div></dl></div></NxCard></div></div>
<NxCard><div class="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--nx-border)] p-5"><div><h2 class="font-bold">Recent Provisioning Jobs</h2><p class="text-sm text-[var(--nx-text-muted)]">Latest activation and verification state</p></div><NxBadge tone="neutral">{{jobs.length}} shown</NxBadge></div><NxTableShell min-width="1050px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase"><tr><th class="px-4 py-3">Job</th><th class="px-4 py-3">Subscriber / Service</th><th class="px-4 py-3">OLT / PON</th><th class="px-4 py-3">ONT</th><th class="px-4 py-3">VLAN</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Created</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody><tr v-if="!jobs.length"><td colspan="8" class="px-4 py-12 text-center text-[var(--nx-text-muted)]">No provisioning jobs found.</td></tr><tr v-for="job in jobs" :key="job.id"><td class="px-4 py-3 font-bold">{{job.job_no||`#${job.id}`}}</td><td class="px-4 py-3">{{job.subscriber_name||'—'}}<div class="text-xs text-[var(--nx-text-muted)]">{{job.service_number||job.ppp_username||'No service'}}</div></td><td class="px-4 py-3">{{job.olt_name||'—'}}<div class="text-xs text-[var(--nx-text-muted)]">{{job.olt_port_label||'No PON'}}</div></td><td class="px-4 py-3 font-mono">{{job.ont_serial||'—'}}</td><td class="px-4 py-3">C {{job.cvlan??'—'}} / S {{job.svlan??'—'}}</td><td class="px-4 py-3"><NxBadge :tone="tone(job.job_status)">{{job.job_status||'UNKNOWN'}}</NxBadge><div class="mt-1 text-xs text-[var(--nx-text-muted)]">{{job.current_stage||'—'}}</div></td><td class="px-4 py-3">{{job.created_at||'—'}}</td><td class="px-4 py-3"><div class="flex justify-end gap-2"><NxButton v-if="job.job_status==='READY'&&job.current_stage==='CREATED'" variant="danger" :disabled="busy" @click="jobAction(job,'cancel')">Cancel</NxButton><NxButton v-if="job.job_status==='VERIFYING'&&['WAITING_FOR_ACS','ACS_PUSH_FAILED'].includes(job.current_stage)" variant="secondary" :disabled="busy" @click="jobAction(job,'check-acs')">Check ACS</NxButton><NxButton v-if="job.job_status==='FAILED'&&job.current_stage==='OLT_PROVISIONING'" variant="secondary" :disabled="busy" @click="jobAction(job,'retry')">Retry OLT</NxButton></div></td></tr></tbody></NxTableShell></NxCard>
<NxModal :open="resultOpen" :title="resultTitle" description="Provisioning operation result" max-width="52rem" @close="resultOpen=false"><pre class="max-h-[55vh] overflow-auto whitespace-pre-wrap p-6 text-xs text-[var(--nx-text)]">{{JSON.stringify(result,null,2)}}</pre><template #footer><NxButton @click="resultOpen=false">Close</NxButton></template></NxModal></div></template>

<style scoped>
:global([data-nx-next-root="service-provisioning"]) { max-width: 100%; overflow-x: hidden; }
</style>
