<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import NxAlert from '../../components/ui/NxAlert.vue';
import NxBadge from '../../components/ui/NxBadge.vue';
import NxButton from '../../components/ui/NxButton.vue';
import NxCard from '../../components/ui/NxCard.vue';
import NxConfirmDialog from '../../components/ui/NxConfirmDialog.vue';
import NxModal from '../../components/ui/NxModal.vue';
import NxPageHeader from '../../components/ui/NxPageHeader.vue';
import NxTableShell from '../../components/ui/NxTableShell.vue';
import NxToolbar from '../../components/ui/NxToolbar.vue';
import { activateAccelConfig, deleteBngSetting, getAccelConfig, getBngRuntime, getBngSetting, getBngSettings, installBootRecovery, previewAccelConfig, saveAccelConfig, saveBngSetting, scanBngHostKey, stageAccelConfig, testBngConnection, trustBngHostKey } from './api';
import type { AccelProfile, BngRuntime, BngRuntimeRow, BngSetting } from './contracts';

type Tab = 'settings' | 'accel' | 'svlan' | 'cvlan' | 'ppp';
type ActionKind = 'test' | 'trust' | 'recovery' | 'delete' | 'stage' | 'activate';
const tab = ref<Tab>('settings'); const search = ref(''); const loading = ref(false); const saving = ref(false);
const error = ref(''); const notice = ref(''); const dialogError = ref(''); const settingOpen = ref(false); const previewOpen = ref(false);
const pendingAction = ref<ActionKind | null>(null); const confirmation = ref(''); const scannedFingerprint = ref('');
const settings = ref<BngSetting[]>([]); const setting = ref<BngSetting>({}); const runtime = ref<BngRuntime>({}); const accelProfile = ref<AccelProfile>({});
const integrationWarnings = ref<string[]>([]); const preview = ref('');
const settingForm = reactive({ enabled: 1, host: '', port: 22, username: '', password: '', bng_parent_interface: '', preferred_interface: '' });
const accelForm = reactive<Record<string, string | number>>({});

const groups = [
  ['Modules and Core', [['modules','Modules (comma separated)','text'],['thread_count','Thread count','number'],['log_error','Error log','text'],['log_debug','Debug log','text'],['log_file','Main log','text'],['log_level','Log level','number']]],
  ['PPPoE', [['pppoe_verbose','Verbose','number'],['pppoe_interface','Interface expression','text'],['vlan_mon','VLAN monitor','text'],['vlan_name','VLAN name','text'],['vlan_timeout','VLAN timeout','number'],['ifname','PPP interface name','text'],['ac_name','AC name','text'],['service_name','Service name','text'],['accept_any_service','Accept any service','number'],['pado_delay','PADO delay','number'],['max_sessions','Maximum sessions','number'],['ip_pool','IP pool','text']]],
  ['PPP and Address Pool', [['default_auth','Default authentication','text'],['ipv4','IPv4 policy','text'],['mtu','MTU','number'],['mru','MRU','number'],['min_mtu','Minimum MTU','number'],['lcp_echo_interval','LCP echo interval','number'],['lcp_echo_failure','LCP echo failure','number'],['ipcp','IPCP','number'],['ipcp_accept_local','Accept local IPCP','number'],['ipcp_accept_remote','Accept remote IPCP','number'],['ppp_verbose','PPP verbose','number'],['pool_gateway','Pool gateway','text'],['pool_range','Pool range','text'],['pool_name','Pool name','text']]],
  ['RADIUS', [['nas_ip_address','NAS IP address','text'],['nas_identifier','NAS identifier','text'],['radius_gateway','Gateway IP address','text'],['radius_server','RADIUS server','text'],['radius_secret','RADIUS secret','password'],['radius_auth_port','Authentication port','number'],['radius_acct_port','Accounting port','number'],['radius_timeout','Timeout','number'],['radius_max_try','Maximum tries','number'],['acct_interim_interval','Interim interval','number'],['radius_verbose','RADIUS verbose','number'],['dae_address','DAE address','text'],['dae_port','DAE port','number'],['dae_secret','DAE secret','password']]],
  ['CLI and Shaper', [['cli_address','CLI bind address','text'],['cli_port','CLI port','number'],['shaper_attr','Shaper attribute','text'],['down_limiter','Download limiter','text'],['up_limiter','Upload limiter','text'],['leaf_qdisc','Leaf qdisc','text']]],
] as const;

const filtered = (rows?: BngRuntimeRow[]) => (rows || []).filter((row) => !search.value.trim() || JSON.stringify(row).toLowerCase().includes(search.value.trim().toLowerCase()));
const svlans = computed(() => filtered(runtime.value.svlan_groups)); const cvlans = computed(() => filtered(runtime.value.client_vlan_interfaces)); const ppps = computed(() => filtered(runtime.value.bng_interfaces));
const actionCopy = computed(() => ({
  test: ['Test BNG connection?', 'This performs a read-only SSH connectivity test.', 'Run Test', ''],
  trust: ['Trust BNG host key?', `Verify this fingerprint through a trusted channel: ${scannedFingerprint.value}`, 'Trust Host Key', scannedFingerprint.value],
  recovery: ['Install boot recovery?', 'This installs and enables desired-state recovery. It does not execute recovery or restart Accel-PPP now.', 'Install Recovery', 'INSTALL BNG BOOT RECOVERY'],
  delete: ['Delete BNG connection?', 'The backend will reject deletion while VLAN, CGNAT, Accel-PPP, or FRR profiles depend on it.', 'Delete BNG', ''],
  stage: ['Stage Accel-PPP configuration?', 'This uploads the saved draft for the next maintenance window. It does not restart Accel-PPP or disconnect subscribers.', 'Stage Configuration', ''],
  activate: ['Activate during maintenance?', 'This restarts Accel-PPP and disconnects active subscriber sessions.', 'Activate and Disconnect', 'ACTIVATE DURING MAINTENANCE'],
}[pendingAction.value || 'test']));
const requiredPhrase = computed(() => actionCopy.value[3]);

function clearMessages() { error.value=''; notice.value=''; dialogError.value=''; }
async function loadAll(showNotice=false) { loading.value=true; clearMessages(); try { const [s,r,a]=await Promise.allSettled([getBngSetting(),getBngRuntime(),getAccelConfig()]); const failures:string[]=[]; if(s.status==='fulfilled'){setting.value=s.value||{};}else{failures.push(s.reason instanceof Error?s.reason.message:'Failed to load BNG settings.');} if(r.status==='fulfilled'){runtime.value=r.value||{};}else{runtime.value={};failures.push(r.reason instanceof Error?r.reason.message:'BNG runtime is unavailable.');} if(a.status==='fulfilled'){const result=a.value;accelProfile.value=result.profile||{};integrationWarnings.value=result.integration_warnings||[];const values={...(result.defaults||{}),...(result.profile?.config||{})};Object.entries(values).forEach(([key,value])=>{if(!['radius_secret','dae_secret'].includes(key))accelForm[key]=Array.isArray(value)?value.join(','):String(value??'');});}else{failures.push(a.reason instanceof Error?a.reason.message:'Failed to load Accel-PPP settings.');} if(failures.length)error.value=failures.join(' ');else if(showNotice)notice.value='BNG runtime refreshed.'; } finally{loading.value=false;} }
function openSetting() { Object.assign(settingForm,{enabled:Number(setting.value.enabled??1),host:setting.value.host||'',port:Number(setting.value.port||22),username:setting.value.username||'',password:'',bng_parent_interface:setting.value.bng_parent_interface||'',preferred_interface:setting.value.preferred_interface||''}); dialogError.value=''; settingOpen.value=true; }
async function submitSetting() { dialogError.value=''; if(!settingForm.host.trim()||!settingForm.username.trim()||!settingForm.bng_parent_interface.trim()){dialogError.value='Host, username, and BNG parent interface are required.';return;} saving.value=true; try{const result=await saveBngSetting({...settingForm,auth_type:'PASSWORD',vlan_mode:'QINQ',auto_create_svlan_interface:1,remarks:''});settingOpen.value=false;notice.value=result.message;await loadAll(false);}catch(reason){dialogError.value=reason instanceof Error?reason.message:'Failed to save BNG.';}finally{saving.value=false;} }
async function submitAccel() { saving.value=true;clearMessages();try{const result=await saveAccelConfig(accelForm);notice.value=result.message||'Accel-PPP draft saved. No restart was performed.';await loadAll(false);}catch(reason){error.value=reason instanceof Error?reason.message:'Failed to save draft.';}finally{saving.value=false;} }
async function showPreview(){clearMessages();try{preview.value=(await previewAccelConfig(accelForm)).data.config||'';previewOpen.value=true;}catch(reason){error.value=reason instanceof Error?reason.message:'Unable to preview the current configuration.';} }
async function requestAction(kind:ActionKind){clearMessages();confirmation.value='';if(kind==='trust'){try{scannedFingerprint.value=(await scanBngHostKey()).fingerprint||'';}catch(reason){error.value=reason instanceof Error?reason.message:'Unable to scan host key.';return;}}pendingAction.value=kind;}
async function executeAction(){if(!pendingAction.value)return;if(requiredPhrase.value&&confirmation.value!==requiredPhrase.value){dialogError.value=`Type ${requiredPhrase.value} exactly to continue.`;return;}saving.value=true;dialogError.value='';try{let message='';if(pendingAction.value==='test')message=(await testBngConnection()).message;if(pendingAction.value==='trust')message=(await trustBngHostKey(scannedFingerprint.value)).message;if(pendingAction.value==='recovery')message=(await installBootRecovery()).message;if(pendingAction.value==='delete')message=(await deleteBngSetting()).message;if(pendingAction.value==='stage')message=(await stageAccelConfig()).message;if(pendingAction.value==='activate')message=(await activateAccelConfig()).message;pendingAction.value=null;notice.value=message;await loadAll(false);}catch(reason){dialogError.value=reason instanceof Error?reason.message:'BNG action failed.';}finally{saving.value=false;} }
function tone(status?:string):'success'|'danger'|'neutral' {return String(status).toUpperCase()==='UP'?'success':String(status).toUpperCase()==='DOWN'?'danger':'neutral';}
onMounted(()=>void loadAll(false));
</script>

<template><div class="space-y-4 pb-8 text-[var(--nx-text)]">
  <NxPageHeader eyebrow="BNG interface console" title="BNG Management" description="Configure the BNG connection and inspect the live S-VLAN, C-VLAN, and PPP interface hierarchy."><template #actions><NxButton variant="secondary" :disabled="loading" @click="loadAll(true)">{{loading?'Refreshing…':'Refresh Runtime'}}</NxButton></template></NxPageHeader>
  <NxAlert v-if="error||notice" :tone="error?'danger':'success'">{{error||notice}}</NxAlert><NxAlert v-for="warning in integrationWarnings" :key="warning" tone="warning">{{warning}}</NxAlert>
  <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><NxCard v-for="item in [['BNG Connection',setting.host||'Not configured',`Parent: ${setting.bng_parent_interface||'—'}`],['S-VLAN Interfaces',svlans.length,'Outer VLAN interfaces'],['C-VLAN Interfaces',cvlans.length,'Subscriber VLAN interfaces'],['PPP Interfaces',ppps.length,'Active PPP sessions']]" :key="String(item[0])"><p class="text-xs font-semibold uppercase text-[var(--nx-text-muted)]">{{item[0]}}</p><p class="mt-2 text-xl font-bold">{{item[1]}}</p><p class="mt-1 text-xs text-[var(--nx-text-muted)]">{{item[2]}}</p></NxCard></section>
  <NxToolbar><div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div role="tablist" class="flex flex-wrap gap-2"><button v-for="item in [['settings','BNG Settings'],['accel','Accel-PPP'],['svlan','S-VLAN BNG Interface'],['cvlan','C-VLAN BNG Interface'],['ppp','PPP Interface']]" :key="item[0]" class="min-h-10 rounded-md px-3 text-sm font-semibold" :class="tab===item[0]?'bg-brand-600 text-white':'bg-[var(--nx-surface-muted)] text-[var(--nx-text)]'" @click="tab=item[0] as Tab">{{item[1]}}</button></div><input v-if="['svlan','cvlan','ppp'].includes(tab)" v-model="search" type="search" placeholder="Search runtime interfaces…" class="min-h-11 min-w-72 rounded-md bg-[var(--nx-surface-muted)] px-4 text-sm"></div></NxToolbar>
  <section v-if="tab==='settings'" class="space-y-3"><div class="flex flex-wrap justify-end gap-2"><NxButton variant="secondary" :disabled="!setting.id" @click="requestAction('recovery')">Install Boot Recovery</NxButton><NxButton variant="secondary" :disabled="!setting.id" @click="requestAction('trust')">Trust Host Key</NxButton><NxButton variant="secondary" :disabled="!setting.id" @click="requestAction('test')">Test Connection</NxButton><NxButton @click="openSetting">{{setting.id?'Edit BNG':'Add BNG'}}</NxButton></div><NxTableShell min-width="900px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase text-[var(--nx-text-muted)]"><tr><th class="px-4 py-3">Host</th><th class="px-4 py-3">Username</th><th class="px-4 py-3">Authentication</th><th class="px-4 py-3">Interfaces</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody><tr v-if="!setting.id"><td colspan="6" class="px-4 py-12 text-center">No BNG connection configured.</td></tr><tr v-else><td class="px-4 py-3"><p class="font-semibold">{{setting.host}}:{{setting.port||22}}</p><p class="text-xs text-[var(--nx-text-muted)]">{{setting.host_key_trusted?(setting.host_key_fingerprint||'Host key trusted'):'Host key not trusted'}}</p></td><td class="px-4 py-3">{{setting.username}}</td><td class="px-4 py-3">Password</td><td class="px-4 py-3"><p>{{setting.bng_parent_interface||'—'}}</p><p class="text-xs text-[var(--nx-text-muted)]">Egress: {{setting.preferred_interface||'Auto'}}</p></td><td class="px-4 py-3"><NxBadge :tone="setting.enabled?'success':'neutral'">{{setting.enabled?'ACTIVE':'INACTIVE'}}</NxBadge></td><td class="px-4 py-3 text-right"><div class="flex justify-end gap-2"><NxButton variant="secondary" @click="openSetting">Edit</NxButton><NxButton variant="danger" @click="requestAction('delete')">Delete</NxButton></div></td></tr></tbody></NxTableShell></section>
  <section v-if="tab==='accel'" class="rounded-lg border border-[var(--nx-border)] bg-[var(--nx-surface)] p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold">Accel-PPP desired configuration</h2><p class="text-sm text-[var(--nx-text-muted)]">Draft changes do not restart Accel-PPP.</p></div><NxBadge :tone="accelProfile.status==='ACTIVE'?'success':accelProfile.status==='STAGED'?'warning':'neutral'">{{accelProfile.status||'NOT CONFIGURED'}}</NxBadge></div><NxAlert tone="warning" class="mt-4">Activation restarts Accel-PPP and disconnects active PPP sessions.</NxAlert><form class="mt-5" @submit.prevent="submitAccel"><section v-for="group in groups" :key="group[0]" class="mb-6"><h3 class="mb-3 font-bold">{{group[0]}}</h3><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label v-for="field in group[1]" :key="field[0]" class="grid gap-1.5 text-sm font-semibold">{{field[1]}}<input v-model="accelForm[field[0]]" :type="field[2]" :placeholder="field[2]==='password'?'Leave blank to keep saved secret':''" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-normal"></label></div></section><div class="flex flex-wrap justify-end gap-2 border-t border-[var(--nx-border)] pt-4"><NxButton type="button" variant="secondary" @click="showPreview">Preview</NxButton><NxButton type="submit" :disabled="saving">Save Draft</NxButton><NxButton type="button" variant="secondary" :disabled="!accelProfile.id" @click="requestAction('stage')">Stage for Maintenance</NxButton><NxButton type="button" variant="danger" :disabled="accelProfile.status!=='STAGED'" @click="requestAction('activate')">Activate Maintenance</NxButton></div></form></section>
  <section v-if="tab==='svlan'"><NxTableShell min-width="760px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase"><tr><th class="px-4 py-3">Interface</th><th class="px-4 py-3">Parent</th><th class="px-4 py-3">S-VLAN</th><th class="px-4 py-3">State</th><th class="px-4 py-3">C-VLANs</th></tr></thead><tbody><tr v-if="!svlans.length"><td colspan="5" class="px-4 py-12 text-center">No S-VLAN BNG interfaces detected.</td></tr><tr v-for="row in svlans" :key="row.interface"><td class="px-4 py-3 font-mono">{{row.interface}}</td><td class="px-4 py-3 font-mono">{{row.parent_interface}}</td><td class="px-4 py-3">{{row.svlan}}</td><td class="px-4 py-3"><NxBadge :tone="tone(row.status)">{{row.status||'UNKNOWN'}}</NxBadge></td><td class="px-4 py-3">{{row.clients?.length||0}}</td></tr></tbody></NxTableShell></section>
  <section v-if="tab==='cvlan'"><NxTableShell min-width="700px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase"><tr><th class="px-4 py-3">Interface</th><th class="px-4 py-3">Parent</th><th class="px-4 py-3">C-VLAN</th><th class="px-4 py-3">State</th></tr></thead><tbody><tr v-if="!cvlans.length"><td colspan="4" class="px-4 py-12 text-center">No C-VLAN BNG interfaces detected.</td></tr><tr v-for="row in cvlans" :key="row.interface"><td class="px-4 py-3 font-mono">{{row.interface}}</td><td class="px-4 py-3 font-mono">{{row.parent_interface}}.{{row.svlan}}</td><td class="px-4 py-3">{{row.cvlan}}</td><td class="px-4 py-3"><NxBadge :tone="tone(row.status)">{{row.status||'UNKNOWN'}}</NxBadge></td></tr></tbody></NxTableShell></section>
  <section v-if="tab==='ppp'"><NxTableShell min-width="1000px"><thead class="bg-[var(--nx-surface-muted)] text-xs uppercase"><tr><th class="px-4 py-3">PPP Interface</th><th class="px-4 py-3">Local Address</th><th class="px-4 py-3">Peer Address</th><th class="px-4 py-3">PPP Username</th><th class="px-4 py-3">Subscriber</th><th class="px-4 py-3">Service ID</th></tr></thead><tbody><tr v-if="!ppps.length"><td colspan="6" class="px-4 py-12 text-center">No active PPP interfaces detected.</td></tr><tr v-for="row in ppps" :key="row.interface"><td class="px-4 py-3 font-mono">{{row.interface}}</td><td class="px-4 py-3 font-mono">{{row.local_address||'—'}}</td><td class="px-4 py-3 font-mono">{{row.peer_address||'—'}}</td><td class="px-4 py-3">{{row.ppp_username||'—'}}</td><td class="px-4 py-3">{{row.subscriber_name||'—'}}</td><td class="px-4 py-3">{{row.service_id||'—'}}</td></tr></tbody></NxTableShell></section>
  <NxModal :open="settingOpen" :title="setting.id?'Edit BNG Connection':'Add BNG Connection'" description="Store SSH access and Linux interface automation settings." @close="settingOpen=false"><form @submit.prevent="submitSetting"><NxAlert v-if="dialogError" tone="danger" class="mx-6 mt-5">{{dialogError}}</NxAlert><div class="grid gap-4 bg-[var(--nx-canvas)] p-6 md:grid-cols-2"><label class="grid gap-1 text-sm font-semibold">Status<select v-model="settingForm.enabled" class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"><option :value="1">Enabled</option><option :value="0">Disabled</option></select></label><label class="grid gap-1 text-sm font-semibold">BNG Host / IP<input v-model="settingForm.host" required class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label><label class="grid gap-1 text-sm font-semibold">SSH Port<input v-model.number="settingForm.port" type="number" min="1" max="65535" required class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label><label class="grid gap-1 text-sm font-semibold">Username<input v-model="settingForm.username" required class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label><label class="grid gap-1 text-sm font-semibold md:col-span-2">Password<input v-model="settingForm.password" type="password" placeholder="Leave blank to keep current password" class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label><label class="grid gap-1 text-sm font-semibold">BNG Parent Interface<input v-model="settingForm.bng_parent_interface" required placeholder="ens17" class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label><label class="grid gap-1 text-sm font-semibold">Preferred Egress Interface<input v-model="settingForm.preferred_interface" placeholder="ens16" class="min-h-11 rounded-md bg-[var(--nx-surface)] px-3"></label></div><div class="flex justify-end gap-2 border-t border-[var(--nx-border)] px-6 py-4"><NxButton type="button" variant="secondary" @click="settingOpen=false">Cancel</NxButton><NxButton type="submit" :disabled="saving">{{saving?'Saving…':'Save BNG'}}</NxButton></div></form></NxModal>
  <NxModal :open="previewOpen" title="Generated Accel-PPP configuration" description="Secrets are redacted." max-width="60rem" @close="previewOpen=false"><pre class="m-6 max-h-[65vh] overflow-auto rounded-md bg-slate-950 p-4 text-xs text-slate-100">{{preview}}</pre><template #footer><NxButton @click="previewOpen=false">Close</NxButton></template></NxModal>
  <NxModal :open="Boolean(pendingAction&&requiredPhrase)" :title="actionCopy[0]" :description="actionCopy[1]" @close="pendingAction=null"><div class="p-6"><NxAlert v-if="dialogError" tone="danger" class="mb-4">{{dialogError}}</NxAlert><label class="grid gap-2 text-sm font-semibold">Type the confirmation phrase<input v-model="confirmation" class="min-h-11 rounded-md bg-[var(--nx-surface-muted)] px-3 font-mono"></label><p class="mt-2 text-xs text-[var(--nx-text-muted)]">Required: <code>{{requiredPhrase}}</code></p></div><template #footer><NxButton variant="secondary" @click="pendingAction=null">Cancel</NxButton><NxButton :variant="pendingAction==='activate'?'danger':'primary'" :disabled="saving" @click="executeAction">{{saving?'Working…':actionCopy[2]}}</NxButton></template></NxModal>
  <NxConfirmDialog :open="Boolean(pendingAction&&!requiredPhrase)" :title="actionCopy[0]" :description="actionCopy[1]" :confirm-label="actionCopy[2]" :busy="saving" :danger="pendingAction==='delete'" :error="dialogError" @close="pendingAction=null" @confirm="executeAction" />
</div></template>
