<script setup lang="ts">
import{computed,defineComponent,h,onMounted,ref}from'vue';import NxAlert from'../../components/ui/NxAlert.vue';import NxButton from'../../components/ui/NxButton.vue';import NxCard from'../../components/ui/NxCard.vue';import NxPageHeader from'../../components/ui/NxPageHeader.vue';import{getJson,postForm}from'../../lib/api';
type Settings={system_name:string;timezone:string;currency:string;date_format:string;time_format:string;subscriber_prefix:string;service_prefix:string;job_prefix:string;invoice_due_days:string;grace_period_days:string;provisioning_mode:string;installation_assignment_mode:string;session_timeout:string;max_login_attempts:string;log_retention_days:string;maintenance_mode:string};
const defaults=():Settings=>({system_name:'NexusBox',timezone:'Asia/Manila',currency:'PHP',date_format:'Y-m-d',time_format:'H:i:s',subscriber_prefix:'SUB',service_prefix:'SVC',job_prefix:'JOB',invoice_due_days:'7',grace_period_days:'3',provisioning_mode:'FULL_AUTO',installation_assignment_mode:'MANUAL',session_timeout:'3600',max_login_attempts:'5',log_retention_days:'30',maintenance_mode:'0'});
const form=ref(defaults()),original=ref(defaults()),loading=ref(false),saving=ref(false),error=ref(''),notice=ref('');const inputClass='min-h-11 w-full rounded-md border border-[var(--nx-border)] bg-[var(--nx-surface)] px-3 text-sm text-[var(--nx-text)] outline-none transition focus:border-[var(--nx-primary)]';const dirty=computed(()=>JSON.stringify(form.value)!==JSON.stringify(original.value));const maintenance=computed({get:()=>form.value.maintenance_mode==='1',set:v=>form.value.maintenance_mode=v?'1':'0'});const Field=defineComponent({props:{label:String},setup(p,{slots}){return()=>h('label',{class:'grid gap-1.5 text-sm font-semibold'},[p.label,slots.default?.()])}});const SectionTitle=defineComponent({props:{title:String,copy:String},setup(p){return()=>h('div',{class:'mb-5'},[h('p',{class:'text-base font-bold'},p.title),h('p',{class:'text-sm text-[var(--nx-text-muted)]'},p.copy)])}});
async function load(show=false){loading.value=true;error.value='';notice.value='';try{const d=await getJson<Partial<Settings>>('/api/v1/system-settings/general');form.value={...defaults(),...d};original.value={...form.value};if(show)notice.value='System settings refreshed.';}catch(e){error.value=e instanceof Error?e.message:'Unable to load system settings.';}finally{loading.value=false;}}
function reset(){form.value={...original.value};notice.value='Unsaved changes discarded.';}
async function save(){saving.value=true;error.value='';notice.value='';try{const data=new FormData();Object.entries(form.value).forEach(([k,v])=>data.set(k,v));const r=await postForm<Settings>('/api/v1/system-settings/general',data);form.value={...defaults(),...r.data};original.value={...form.value};notice.value=r.message||'System settings saved.';}catch(e){error.value=e instanceof Error?e.message:'Unable to save system settings.';}finally{saving.value=false;}}
onMounted(()=>void load());
</script>
<template><div class="space-y-4 overflow-x-hidden pb-8 text-[var(--nx-text)]"><NxPageHeader eyebrow="Platform configuration" title="System Settings" description="Application-wide operational, billing, security, and provisioning defaults."><template #actions><NxButton variant="secondary" :disabled="loading||saving" @click="load(true)">{{loading?'Refreshing…':'Refresh'}}</NxButton><NxButton :disabled="loading||saving||!dirty" @click="save">{{saving?'Saving…':'Save Settings'}}</NxButton></template></NxPageHeader><NxAlert v-if="error||notice" :tone="error?'danger':'success'">{{error||notice}}</NxAlert><div v-if="dirty" class="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-amber-400/40 bg-amber-400/10 px-4 py-3 text-sm"><span><b>Unsaved configuration</b> — changes take effect only after saving.</span><NxButton variant="secondary" @click="reset">Discard changes</NxButton></div>
<div class="grid gap-4 xl:grid-cols-2"><NxCard><SectionTitle title="General" copy="Regional formats and the name shown by the application."/><div class="grid gap-4 md:grid-cols-2"><Field label="System name" class="md:col-span-2"><input v-model="form.system_name" required :class="inputClass"></Field><Field label="Timezone"><select v-model="form.timezone" :class="inputClass"><option>Asia/Manila</option><option>UTC</option></select></Field><Field label="Currency"><select v-model="form.currency" :class="inputClass"><option>PHP</option><option>USD</option></select></Field><Field label="Date format"><select v-model="form.date_format" :class="inputClass"><option>Y-m-d</option><option>m/d/Y</option><option>d/m/Y</option></select></Field><Field label="Time format"><select v-model="form.time_format" :class="inputClass"><option>H:i:s</option><option>h:i A</option></select></Field></div></NxCard>
<NxCard><SectionTitle title="Numbering and billing" copy="Prefixes for generated records and default payment timing."/><div class="grid gap-4 md:grid-cols-3"><Field label="Subscriber prefix"><input v-model="form.subscriber_prefix" required :class="inputClass"></Field><Field label="Service prefix"><input v-model="form.service_prefix" required :class="inputClass"></Field><Field label="Job prefix"><input v-model="form.job_prefix" required :class="inputClass"></Field><Field label="Invoice due days" class="md:col-span-3 lg:col-span-1"><input v-model="form.invoice_due_days" type="number" min="0" max="365" :class="inputClass"></Field><Field label="Grace period days" class="md:col-span-3 lg:col-span-1"><input v-model="form.grace_period_days" type="number" min="0" max="365" :class="inputClass"></Field></div></NxCard></div>
<NxCard><SectionTitle title="Operations and security" copy="Provisioning behavior, sessions, authentication limits, and data retention."/><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Provisioning mode"><select v-model="form.provisioning_mode" :class="inputClass"><option>FULL_AUTO</option><option>ASSISTED</option><option>MANUAL</option></select></Field><Field label="Installation assignment"><select v-model="form.installation_assignment_mode" :class="inputClass"><option value="MANUAL">Manual dispatch</option><option value="AUTO_NEAREST">Nearest technician</option></select></Field><Field label="Session timeout (seconds)"><input v-model="form.session_timeout" type="number" min="300" max="86400" :class="inputClass"></Field><Field label="Maximum login attempts"><input v-model="form.max_login_attempts" type="number" min="1" max="100" :class="inputClass"></Field><Field label="Log retention days"><input v-model="form.log_retention_days" type="number" min="1" max="3650" :class="inputClass"></Field></div><div class="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[var(--nx-border)] bg-[var(--nx-surface-muted)] p-4"><div><p class="font-bold">Maintenance mode</p><p class="text-sm text-[var(--nx-text-muted)]">Restrict normal application access while maintenance is underway.</p></div><button type="button" role="switch" :aria-checked="maintenance" class="relative h-7 w-12 rounded-full transition" :class="maintenance?'bg-amber-500':'bg-[var(--nx-border)]'" @click="maintenance=!maintenance"><span class="absolute top-1 size-5 rounded-full bg-white shadow transition-all" :class="maintenance?'left-6':'left-1'"></span><span class="sr-only">Toggle maintenance mode</span></button></div></NxCard></div></template>
<style scoped>:global([data-nx-next-root="system-settings"]){max-width:100%;overflow-x:hidden}</style>
